let shopItemsData = [
  {
    id: "Paracetamol",
    name: "Paracetamol",
    price: 5,
    desc: "Pain reliever and fever reducer",
    img: "img1.png",
  },
  {
    id: "Amoxicillin",
    name: "Amoxicillin",
    price: 10,
    desc: "Antibiotic for bacterial infections",
    img: "img2.png",
  },
  {
    id: "Aspirins",
    name: "Aspirins",
    price: 3,
    desc: "Pain reliever, fever reducer, and blood thinner",
    img: "img3.png",
  },
  {
    id: "Ibuprofens",
    name: "Ibuprofen",
    price: 8,
    desc: "Pain reliever, fever reducer, and anti-inflammatory",
    img: "img4.png",
  },
  {
    id: "Lisinoprils",
    name: "Lisinopril",
    price: 15,
    desc: "ACE inhibitor for high blood pressure and heart failure",
    img: "img5.png",
  },
  {
    id: "Metformin",
    name: "Metformin",
    price: 12,
    desc: "Imgication for type 2 diabetes",
    img: "img6.png",
  },
  {
    id: "Simvastatinn",
    name: "Simvastatin",
    price: 20,
    desc: "Imgication to lower cholesterol levels",
    img: "img7.png",
  },
  {
    id: "Losartan",
    name: "Losartan",
    price: 18,
    desc: "ARB for high blood pressure and kidney protection",
    img: "img8.png",
  },
  {
    id: "Albuterol",
    name: "Albuterol",
    price: 25,
    desc: "Bronchodilator for asthma and COPD",
    img: "img9.jpeg",
  },
  {
    id: "Acetaminophen",
    name: "Acetaminophen",
    price: 6,
    desc: "Pain reliever and fever reducer",
    img: "img10.jpeg",
  },
  {
    id: "Atorvastatin",
    name: "Atorvastatin",
    price: 22,
    desc: "Imgication to lower cholesterol levels",
    img: "img11.png",
  },
  {
    id: "Clopidogrel",
    name: "Clopidogrel",
    price: 30,
    desc: "Blood thinner to prevent heart attack and stroke",
    img: "img12.png",
  },
  {
    id: "Fluticasone",
    name: "Fluticasone",
    price: 15,
    desc: "Steroid imgication for asthma and allergies",
    img: "img13.png",
  },
  {
    id: "Omeprazole",
    name: "Omeprazole",
    price: 18,
    desc: "Proton pump inhibitor for acid reflux and GERD",
    img: "img14.png",
  },
  {
    id: "Metoprolol",
    name: "Metoprolol",
    price: 16,
    desc: "Beta blocker for high blood pressure and heart failure",
    img: "img15.png",
  },
{
  id: "Ibuprofen",
  name: "Ibuprofen Tablets",
  price: 10,
  desc: "Relieve mild to moderate pain, reduce fever and inflammation",
  img: "img16.png",
},
{
  id: "Aspirin",
  name: "Aspirin Tablets",
  price: 5,
  desc: "Relieve mild to moderate pain, reduce fever, and prevent blood clots",
  img: "img17.png",
},
{
  id: "Acetaminophens",
  name: "Acetaminophen Tablets",
  price: 8,
  desc: "Relieve mild to moderate pain and reduce fever",
  img: "img18.png",
},
{
  id: "Naproxen",
  name: "Naproxen Tablets",
  price: 12,
  desc: "Relieve mild to moderate pain, reduce fever, and reduce inflammation",
  img: "img19.png",
},
{
  id: "Loratadine",
  name: "Loratadine Tablets",
  price: 7,
  desc: "Relieve symptoms of hay fever, allergies, and hives",
  img: "img20.png",
},
{
  id: "Diphenhydramine",
  name: "Diphenhydramine Tablets",
  price: 6,
  desc: "Relieve symptoms of hay fever, allergies, and the common cold",
  img: "img21.png",
},
{
  id: "Calcium",
  name: "Calcium Supplements",
  price: 15,
  desc: "Help maintain strong bones and teeth, and support muscle and nerve function",
  img: "img22.jpeg",
},
{
  id: "Multivitamin",
  name: "Multivitamin Supplements",
  price: 20,
  desc: "Provide essential vitamins and minerals for overall health and wellness",
  img: "img23.jpeg",
},
{
  id: "Omega",
  name: "Omega-3 Supplements",
  price: 25,
  desc: "Support heart health, brain function, and reduce inflammation",
  img: "img24.png",
},
{
  id: "Probiotic",
  name: "Probiotic Supplements",
  price: 18,
  desc: "Support digestive health and boost the immune system",
  img: "img25.png",
},
{
  id: "VitaminD",
  name: "Vitamin D Supplements",
  price: 12,
  desc: "Help maintain strong bones and teeth, and support immune system function",
  img: "img26.jpeg",
},
{
  id: "Iron",
  name: "Iron Supplements",
  price: 9,
  desc: "Treat iron deficiency anemia and improve energy levels",
  img: "img27.png",
},
{
  id: "Melatonin",
  name: "Melatonin Supplements",
  price: 7,
  desc: "Promote healthy sleep and regulate the sleep-wake cycle",
  img: "img28.png",
},
{
  id: "Magnesium",
  name: "Magnesium Supplements",
  price: 11,
  desc: "Support nerve and muscle function, regulate blood sugar levels, and promote heart health",
  img: "img29.png",
},
{
  id: "VitaminC",
  name: "Vitamin C Supplements",
  price: 8,
  desc: "Boost the immune system, promote healthy skin, and improve iron absorption",
  img: "img30.png",
},
  {
    id: "Nurofen",
    name: "Nurofen",
    price: 12.99,
    desc: "Effective pain relief for headaches, migraines, and back pain.",
    img: "img31.jpeg",
  },
  {
    id: "Calpol",
    name: "Calpol",
    price: 5.99,
    desc: "Soothes pain and reduces fever in children.",
    img: "img32.jpeg",
  },
  {
    id: "Lemsip",
    name: "Lemsip",
    price: 7.99,
    desc: "Relieves cold and flu symptoms such as headache, fever, and sore throat.",
    img: "img33.jpeg",
  },
  {
    id: "Beechams",
    name: "Beechams",
    price: 9.99,
    desc: "Powerful relief for symptoms of cold and flu.",
    img: "img34.jpeg",
  },
  {
    id: "Sudafed",
    name: "Sudafed",
    price: 8.99,
    desc: "Clears nasal congestion and relieves sinus pressure.",
    img: "img35.jpeg",
  },
  {
    id: "Panadol",
    name: "Panadol",
    price: 6.99,
    desc: "Relieves mild to moderate pain and reduces fever.",
    img: "img36.png",
  },
  {
    id: "Advil",
    name: "Advil",
    price: 10.99,
    desc: "Powerful pain relief for headaches, menstrual cramps, and arthritis.",
    img: "img37.png",
  },
  {
    id: "Aleve",
    name: "Aleve",
    price: 8.49,
    desc: "Relieves pain and inflammation caused by arthritis, menstrual cramps, and other conditions.",
    img: "img38.jpg",
  },
  {
    id:  "Claritin",
    name: "Claritin",
    price: 11.99,
    desc: "Provides relief from allergies such as hay fever, hives, and itching.",
    img: "img39.png",
  },
  {
    id:  "Zyrtec",
    name: "Zyrtec",
    price: 12.99,
    desc: "Reduces symptoms of allergies such as sneezing, runny nose, and watery eyes.",
    img: "img40.jpeg",
  },
  {
    id:  "Benadryl",
    name: "Benadryl",
    price: 9.99,
    desc: "Relieves allergy symptoms such as itching, hives, and watery eyes.",
    img: "img41.png",
  },
  {
    id: "Rhinocort",
    name: "Rhinocort",
    price: 16.99,
    desc: "Provides relief from nasal allergy symptoms such as congestion and runny nose.",
    img: "img42.png",
  },
  {
    id:  "Nasonex",
    name: "Nasonex",
    price: 19.99,
    desc: "Relieves nasal allergy symptoms such as congestion, runny nose, and sneezing.",
    img: "img43.jpg",
  },
  {
    id: "Flonase",
    name: "Flonase",
    price: 17.99,
    desc: "Treats nasal allergy symptoms such as congestion, runny nose, and sneezing.",
    img: "img44.jpeg"
},

{
  id: "Omeprazolee",
  name: "Omeprazole",
  price: 15,
  desc: "Omeprazole is used to treat certain stomach and esophagus problems.",
  img: "img45.png"
},
{
  id: "Lisinopril",
  name: "Lisinopril Tablets",
  price: 8,
  desc: "Lisinopril is used to treat high blood pressure.",
  img: "img46.png"
},
{
  id: "Simvastatin",
  name: "Simvastatin",
  price: 12,
  desc: "Simvastatin is used to lower cholesterol and triglycerides.",
  img: "img47.png"
},
{
  id:  "Hydrocodone",
  name: "Hydrocodone",
  price: 20,
  desc: "Hydrocodone is used to relieve moderate to severe pain.",
  img: "img48.png"
},
{
  id:  "Sertraline",
  name: "Sertraline",
  price: 18,
  desc: "Sertraline is used to treat depression, panic attacks, and anxiety disorders.",
  img: "img49.jpeg"
},
{
  id:  "Ciprofloxacin",
  name: "Ciprofloxacin",
  price: 14,
  desc: "Ciprofloxacin is used to treat bacterial infections.",
  img: "img50.png"
},
];

